name: EasyAuction
author: Vestri
description: EasyAuction
version: 0.3
api-version: 1.15
main: ea.java.EasyAuction
permissions:
  ea.admin:
    description: admin
    default: op
  ea.player:
    description: changename
    default: op
commands:
  auction:
    description: auction
    usage: /auction
  auctionadmin:
    description: auctionadmin
    usage: /auctionadmin
