name: EasyAuction
author: Vestri
description: EasyAuction
version: 0.6
api-version: 1.15
main: ea.java.EasyAuction
depend: [Vault]
permissions:
  ea.admin:
    description: admin
    default: op
  ea.player:
    description: changename
    default: op
commands:
  auction:
    description: auction
    usage: /auction
    aliases: [auktion]
  bid:
    description: bid
    usage: /bid <sum>
    aliases: [bieten]
  auctionadmin:
    description: auctionadmin
    usage: /auctionadmin
    aliases: [auktionadmin]
